- name: Gather /etc/fstab from all servers
  hosts: all
  become: true
  tasks:
    - name: Read /etc/fstab content
      slurp:
        src: /etc/fstab
      register: fstab_content

    - name: Format result with hostname
      delegate_to: localhost
      run_once: true
      copy:
        dest: "./fstab_{{ lookup('pipe', 'date +%Y%m%d') }}.txt"
        content: |
          {% for host in ansible_play_batch %}
          ===== {{ host }} =====
          {{ hostvars[host]['fstab_content']['content'] | b64decode }}

          {% endfor %}
